### ISSUE TITLE
Allow overriding of args via k8s yaml file?

### ISSUE THREAD

**Issue by donspaulding** [smileisak/docker-images#3]
Hi there,

I've got a chart which is based off of the [stable/redis-ha chart](https://github.com/kubernetes/charts/tree/master/stable/redis-ha/templates), which uses the image built from this repo, I believe.  I'd like to pass in arguments to the redis-server (`--maxmemory 256mb`, `--maxmemory-policy noeviction`, etc.).  

Is there a reason why `run.sh` doesn't pass along whatever args happen to be passed in via `$@`?

**Comment by smileisak** [comment]
Hi @donspaulding, thank you for your idea. I just forgot to put it. :smile: . I've added `$@` in all versions. check it out. 
https://github.com/smileisak/docker-images/blob/redis-4.0.6/redis/alpine/run.sh#L22
https://github.com/smileisak/docker-images/blob/redis-4.0.6/redis/alpine/run.sh#L51
https://github.com/smileisak/docker-images/blob/redis-4.0.6/redis/alpine/run.sh#L74

**Comment by ianmaddox** [comment]
Changes included in latest PR that was merged in as well. Should be good to go!
