### ISSUE TITLE
Disable Transparent Huge Pages

### ISSUE THREAD

**Issue by frekw** [smileisak/docker-images#5]
During startup, the image issues the following warning:

```
 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
```

It can be detrimental to Redis' performance, more info here: http://antirez.com/news/84

Should probably be a oneliner to add it to `run.sh`.

**Comment by viglesiasce** [comment]
@frekw I believe this can only be changed at the host kernel level, not in the container image since THP is a kernel parameter.

**Comment by frekw** [comment]
Ok, closing this then!

**Comment by ianmaddox** [comment]
Yep, what @viglesiasce said is correct. I tried the command it suggested but that doesn't work in the image.
